export const getCharts = (data, entries) => {
  return [
    {
      label: "Total Weight Change",
      tooltipName: "Total Change",
      desc: "This chart shows your AVERAGED weight change over time. This will tell you how much your weight has changed over time. You can cross reference this with your total caloric change below to see if it is consistent.",
      data: data,
      xAxisKey: "date",
      dataKey: "totalWeightChange",
      unit: "lbs",
    },
    {
      label: "Total ESTIMATED Caloric Change",
      tooltipName: "Total Change",
      desc: "This chart shows your total caloric intake over time based on your ESTIMATED calories. This will tell you if you ate more or less calories than your ESTIMATED calories over time.",
      data: data,
      xAxisKey: "date",
      dataKey: "totalCaloricBasalDiff",
      unit: "kcals",
    },
    {
      label: "Total AVERAGED Caloric Change",
      tooltipName: "Total Change",
      desc: "This chart shows your total caloric intake over time based on your AVERAGED calories. This will tell you if you are generally eating more or less over time.",
      data: data,
      xAxisKey: "date",
      dataKey: "totalCaloricDiff",
      unit: "kcals",
    },
    {
      label: "Daily Weight",
      tooltipName: "Weight",
      desc: "This chart shows your daily recorded weight.",
      data: entries,
      xAxisKey: "date",
      dataKey: "weight",
      unit: "lbs",
    },
    {
      label: "Daily Weight Change",
      tooltipName: "Daily Change",
      desc: "This chart shows your AVERAGED weight change per day. This will tell you how consistent your weight is per day. You should not really see large changes.",
      data: data,
      xAxisKey: "date",
      dataKey: "dailyWeightChange",
      unit: "lbs",
    },
    {
      label: "Daily Caloric Intake",
      tooltipName: "",
      desc: "This chart shows your daily recorded calories. This will tell you how consistenly you are eating. (cross-reference with 'Daily Actual Caloric Change')",
      data: entries,
      xAxisKey: "date",
      dataKey: "calories",
      unit: "kcals",
    },
    {
      label: "Daily Actual Caloric Change",
      tooltipName: "Daily Change",
      desc: "This chart shows your ACTUAL (what you recorded) caloric intake change per day. This will tell you how consistently you are intaking calories per day. Smaller variance means your intake is more consistent, Larger variance means your intake is more varied. (cross-reference with 'Daily Caloric Intake')",
      data: data,
      xAxisKey: "date",
      dataKey: "dailyActualCaloricChange",
      unit: "kcals",
    },
    // {
    //   label: "Daily Averaged Caloric Change",
    //   tooltipName: "Daily Change",
    //   desc: "This chart shows your AVERAGED caloric intake change per day. This will tell you if your base caloric expenditure is going up or down each day.",
    //   data: data,
    //   xAxisKey: "date",
    //   dataKey: "dailyCaloricChange",
    //   unit: "kcals",
    // },
  ];
};
